## Replace these with prod values and encrypt

# The OAUTH tokens are callbacks to a quarry.local domain
# it is ok that they are public.
OAUTH_CONSUMER_TOKEN: "deeb8dbabbf157cb0ed120b89971d800"
OAUTH_SECRET_TOKEN: "38fdce038bbf848453a856aa329f8a06c456c791"
SECRET_KEY: 'aaarggghhpleaserescuemeiamstuckinarandomnumbergeneratorfactory'
DEBUG: True
DB_HOST: 'db'
DB_NAME: 'quarry'
DB_USER: 'quarry'
DB_PASSWORD: 'quarry'
broker_url: 'redis://redis'
result_backend: 'redis://redis'
worker_concurrency: 24  # Since all tasks are IO bound
task_acks_late: True  # Tasks are idempotent!
task_track_started: True
worker_prefetch_multiplier: 1 # Tasks can run for a long time
# Just query the quarry database itself.
REPLICA_DOMAIN: ''
REPLICA_HOST: 'mywiki'
REPLICA_DB: 'mywiki_p'
REPLICA_USER: 'repl'
REPLICA_PASSWORD: 'repl'
REPLICA_PORT: 3306
OUTPUT_PATH_TEMPLATE: '/results/%s/%s/%s.sqlite'
REDIS_HOST: 'redis'
REDIS_PORT: 6379
REDIS_DB: 0
QUERY_TIME_LIMIT: 60  # 1 minute
QUERY_RESULTS_PER_PAGE: 50
KILLER_LOG_PATH: 'killer.log'
MAINTENANCE_MSG: 'This is your local development environment.'
