localdev:
  enabled: false

web:
  replicas: 1
  memory: "300Mi"
  cpu: "100m"
worker:
  replicas: 1
  memory: "700Mi"
  cpu: "100m"

nfs:
#  server: 172.16.4.142
  server: k8s-test-nfs.quarry.eqiad1.wikimedia.cloud
