version: "3.3"

services:

  web:
    build: .
    # To mimic a production runtime, uncomment:
    # entrypoint: ["gunicorn", "-w", "2", "--bind", "0.0.0.0:5000", "wsgi:application"]
    entrypoint: ["python", "wsgi.py"]
    volumes:
      - .:/app
      - results:/results
    ports:
      - "5000:5000"
    depends_on:
      - "db"
      - "mywiki"
      - "redis"

  worker:
    build: .
    volumes:
      - .:/app
      - results:/results
    entrypoint: ["celery", "--app", "quarry.web.worker", "worker", ]
    extra_hosts:
    - "host.docker.internal:host-gateway"
    depends_on:
      - "db"
      - "redis"

  redis:
    image: redis:alpine

  # wikireplica simulator
  mywiki:
    image: mariadb:10.4-focal
    volumes:
      - ./docker-replica/replica.sql:/docker-entrypoint-initdb.d/replica.sql
    environment:
      MYSQL_USER: repl
      MYSQL_PASSWORD: repl
      MYSQL_DATABASE: repl
      MYSQL_RANDOM_ROOT_PASSWORD: 1

  db:
    image: mariadb:10.1.48-bionic
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    environment:
      MYSQL_USER: quarry
      MYSQL_PASSWORD: quarry
      MYSQL_DATABASE: quarry
      MYSQL_RANDOM_ROOT_PASSWORD: 1

volumes:
     results:
