[tox]
envlist = py3-{flake8, pytest, black, mypy}
skip-missing-interpreters = False
isolated_build = True

[flake8]
exclude = bin,lib,include,.venv,.tox,dist,doc,build,*.egg
max-line-length = 120

[mypy]
ignore_missing_imports = True
warn_redundant_casts = True
warn_unused_ignores = True
warn_unreachable = True
warn_unused_configs = True

[testenv]
allowlist_externals = poetry
commands_pre =
    poetry install --no-root --sync --with test
commands =
    pytest: poetry run python -m pytest --cov=quarry -ra {posargs}
    flake8: poetry run flake8
    black: poetry run black --check --diff .
    mypy: poetry run mypy quarry --config-file tox.ini
    format: poetry run black .
