apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
{{ if .Values.localdev.enabled }}
  config.yaml: {{ .Files.Get "dev_config.yaml" | quote }}
{{ else }}
  config.yaml: {{ .Files.Get "prod_config.yaml" | quote }}
{{ end }}
