apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  serviceName: redis
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:alpine3.18
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /data
              name: redis-data
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
          ports:
            - containerPort: 6379
        - name: redis-exporter
          image: {{ .Values.redis.exporter.image }}
          securityContext:
            runAsUser: 59000
            runAsGroup: 59000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
            - containerPort: 30121
      volumes:
        - name: redis-data
          emptyDir:
            sizeLimit: {{ .Values.redis.resources.limits.memory }}
