apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  labels:
    app: redis
spec:
  ports:
    - name: web
      port: 9121
      nodePort: 30121
      protocol: TCP
      targetPort: 9121
  selector:
    app: redis
  type: NodePort
