---

name: Tox

'on':
  pull_request:

jobs:
  tox:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install redis
        run: |
          sudo apt-get update
          sudo apt-get install -y redis
      - name: Install tox
        run: pip install tox
      - name: Run tox
        run: |
          tox
